image: gabrielaraujof/angular-cli

variables:

services:
all_tests:
  script:
   - cd graphical-ide-client && npm install -f
   - ng build --target=production --environment=prod
   - cd ..
   - cd graphical-ide-backend && npm install -f

