image: angular-cli:1.0.0-beta.19

variables:

services:
all_tests:
  script:
   - cd graphical-ide-client && npm install -f
   - ng build --target=production --environment=prod
   - cd ..
   - cd graphical-ide-backend && npm install -f

